{
    'name': 'Customer Document Management',
    'version': '1.0',
    'summary': 'Quản lý khách hàng và văn bản số hóa',
    'author': 'FitDNU',
    'category': 'Tools',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/sequence_contract.xml',
        'data/sequence_document.xml',
        'data/customer_demo.xml',
        'data/document_demo.xml',
        'views/customer_views.xml',
        'views/document_views.xml',
        'views/document_file_views.xml',
        'views/contract_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}